/// <reference types="nativewind/types" />

declare module "nativewind" {
  interface CustomColorScheme {
    colorScheme: "light" | "dark";
  }
}

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.
